---
driver:
  name: docker

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: secret

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - kitchen-issue-751::default
    attributes:
